// This file is generated by ./make.dart

class BuildData {
  static const String name = "ServerDog";
  static const int build = 100;
  static const String engine = "3.10.0";
  static const String buildAt = "2023-05-16 13:08:47.993479";
  static const String IOS_APP_ID = "1586449703";
  static const int modifications = 3;
}
