// This file is generated by ./make.dart

class BuildData {
  static const String name = "TestBox";
  static const int build = 100;
  static const String engine = "3.10.0";
  static const String buildAt = "2023-05-15 15:55:23.766801";
  static const String IOS_APP_ID = "1586449703";
  static const int modifications = 5;
}
