// This file is generated by ./make.dart

class BuildData {
  static const String name = "ServerDog";
  static const int versionCode = 100;
  static const String versionName = "1.0.0";
  static const String engine = "3.10.0";
  static const String buildAt = "2023-06-07 16:17:24.048086";
  static const String IOS_APP_ID = "1586449703";
}
